import { defineNuxtPlugin } from '#app';
import { FormsPlugin, registerRules } from '@overgaming/valiform';
// Generated by the valiform Nuxt module — contains pluginOptions and customRules
// @ts-ignore virtual module resolved by Nuxt at build time
import { pluginOptions, customRules } from '#build/valiform/options.mjs';

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.use(FormsPlugin, pluginOptions);
  if (customRules) registerRules(customRules);
});
